version: '3.8'
services:
  cities-picker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    environment:
      - BINAFLOW_SCHEMA_DIRECTORY=/proto-schema
      - SPRING_WEB_RESOURCES_STATIC_LOCATIONS=file:frontend-js
    volumes:
      - ./world_cities.csv:/world_cities.csv